version: '3'
services:
  web:
    build: ./web
    ports:
      - '80:80'
    depends_on:
      - api
  api:
    build: ./api/src
    ports:
      - '8080:8080'
    environment:
      - POSTGRES_CONNECTION_STRING=Host=postgres;Database=silly;Username=silly;Password=silly
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    expose:
      - '5432'
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=silly
      - POSTGRES_PASSWORD=silly
      - POSTGRES_DB=silly  
volumes:
  pgdata:
