databases:
- db_name: silly
  db_user: silly
  engine: PG
  name: silly
  version: "12"
name: sillytodonet
region: ams
services:
- cors:
    allow_origins:
    - regex: /*
  dockerfile_path: web/Dockerfile
  github:
    branch: master
    deploy_on_push: true
    repo: hellgrenj/SillyTodo.Net
  http_port: 80
  instance_count: 1
  instance_size_slug: basic-xxs
  name: frontend
  routes:
  - path: /
  source_dir: web
- cors:
    allow_origins:
    - regex: /*
  dockerfile_path: api/src/Dockerfile
  envs:
  - key: POSTGRES_CONNECTION_STRING
    scope: RUN_AND_BUILD_TIME
    value: Host= REPLACE WITH REAL HOST ;PORT=25060;Database=silly;Username=silly;Password=REPLACE WITH REAL PWD;SSLMODE=Require;TrustServerCertificate=true # replace host and password
  github:
    branch: master
    deploy_on_push: true
    repo: hellgrenj/SillyTodo.Net
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: api
  routes:
  - path: /api
  source_dir: api/src